#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"

DOCKER_INSTALED=0
FLATPAK_INSTALLED=0
ZOOM_INSTALLED=0

[ -f /usr/bin/docker ] && DOCKER_INSTALLED=1
[ -f /usr/bin/flatpak ] && FLATPAK_INSTALLED=1
[ -f /usr/bin/zoom ] && ZOOM_INSTALLED=1

echo "Installing"...

echo "* Enabling dash"
sudo pacman -S --needed --noconfirm dash dashbinsh checkbashisms

echo "* Defining Sysctl"
sudo cp "$BASEDIR/settings/sysctl/dmesg_restrict.conf" /etc/sysctl.d/dmesg_restrict.conf
sudo cp "$BASEDIR/settings/sysctl/harden_bpf.conf" /etc/sysctl.d/harden_bpf.conf
sudo cp "$BASEDIR/settings/sysctl/kptr_restrict.conf" /etc/sysctl.d/kptr_restrict.conf
sudo cp "$BASEDIR/settings/sysctl/ptrace_scope.conf" /etc/sysctl.d/ptrace_scope.conf
sudo cp "$BASEDIR/settings/sysctl/tcp_hardening.conf" /etc/sysctl.d/tcp_hardening.conf

#If zoom, docker, installed don't put this on
sudo cp "$BASEDIR/settings/sysctl/unprivileged_userns_clone.conf" /etc/sysctl.d/unprivileged_userns_clone.conf
[ "$DOCKER_INSTALED" -eq 1 ] && rm /etc/sysctl.d/unprivileged_userns_clone.conf

#if zoom installed don't put this on
sudo cp "$BASEDIR/settings/sysctl/kexec.conf" /etc/sysctl.d/kexec.conf
[ "$ZOOM_INSTALLED" -eq 1 ] && rm /etc/sysctl.d/kexec.conf


echo "* Enabling IPV6 Privacy"
sudo cp "$BASEDIR/settings/networkmanager/ip6-privacy.conf" /etc/NetworkManager/conf.d/ip6-privacy.conf

echo "* Enabling MAC Privacy"
sudo cp "$BASEDIR/settings/networkmanager/wifi_rand_mac.conf" /etc/NetworkManager/conf.d/wifi_rand_mac.conf

echo "* Configuring network availibility check"
sudo cp "$BASEDIR/settings/networkmanager/connectivity-test.conf" /etc/NetworkManager/conf.d/connectivity-test.conf

echo "* Hardening SSH" 
sudo cp "$BASEDIR/settings/sshd/01_ProhibitPermitRootLogin.conf" /etc/ssh/sshd_config.d/01_ProhibitPermitRootLogin.conf 
sudo cp "$BASEDIR/settings/sshd/02_MaxAuthTries.conf" /etc/ssh/sshd_config.d/02_MaxAuthTries.conf
sudo cp "$BASEDIR/settings/sshd/03_LoginGraceTime.conf" /etc/ssh/sshd_config.d/03_LoginGraceTime.conf
sudo cp "$BASEDIR/settings/sshd/04_PasswordAuthentication.conf" /etc/ssh/sshd_config.d/04_PasswordAuthentication.conf
sudo cp "$BASEDIR/settings/sshd/05_PermitEmptyPasswords.conf" /etc/ssh/sshd_config.d/05_PermitEmptyPasswords.conf 
sudo cp "$BASEDIR/settings/sshd/06_AlternateAuthentication.conf" /etc/ssh/sshd_config.d/06_AlternateAuthentication.conf
sudo cp "$BASEDIR/settings/sshd/07_X11Forwarding.conf" /etc/ssh/sshd_config.d/07_X11Forwarding.conf
sudo cp "$BASEDIR/settings/sshd/08_PermitUserEnvironment.conf" /etc/ssh/sshd_config.d/08_PermitUserEnvironment.conf
sudo cp "$BASEDIR/settings/sshd/09_Tunnelling.conf" /etc/ssh/sshd_config.d/09_Tunnelling.conf

echo "* Installing Network Manager Hook"
sudo cp "$BASEDIR/hooks/networkmanager/10-update-timesyncd" /etc/NetworkManager/dispatcher.d/10-update-timesyncd 

echo "* Installing Btrfs Scrub"
sudo cp "$BASEDIR/units/btrfs-scrub/btrfs-scrub.service" /etc/systemd/system/
sudo cp "$BASEDIR/units/btrfs-scrub/btrfs-scrub.timer" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now btrfs-scrub.timer

echo "* Installing Pacman Sync"
sudo cp "$BASEDIR/units/pacman-sync/pacman-sync.service" /etc/systemd/system/
sudo cp "$BASEDIR/units/pacman-sync/pacman-sync.timer" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now pacman-sync.timer

echo "* Installng firejail"
sudo pacman -S --needed --noconfirm firejail
[ ! -d "$HOME/.config/firejail" ] && mkdir -p "$HOME/.config/firejail"
cp "$BASEDIR/settings/firejail/git.local" "$HOME/.config/firejail/git.local"
cp "$BASEDIR/settings/firejail/ssh.local" "$HOME/.config/firejail/ssh.local"

echo "* Installing Fail2ban"
sudo pacman -S --needed --noconfirm fail2ban
sudo systemctl enable --now fail2ban

echo "* Installing firewalld"
sudo pacman -S --needed --noconfirm firewalld
sudo systemctl enable --now firewalld
# Allow SSH ONLY from private networks
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="22" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="22" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="22" accept'

echo "* Enabling ssh-agent"
systemctl enable --now --user ssh-agent

echo "* Enabling reflector"
sudo pacman -S --needed --noconfirm reflector
sudo cp "$BASEDIR/settings/reflector/reflector.conf" /etc/xdg/reflector/reflector.conf
# At startup
sudo systemctl enable --now reflector.service
# Weekly if still on
sudo systemctl enable --now reflector.timer

echo "Done"
