#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"


sudo cp "$BASEDIR/auto-update.service" /etc/systemd/system/auto-update.service
sudo cp "$BASEDIR/auto-update.timer" /etc/systemd/system/auto-update.timer

sudo systemctl daemon-reload

sudo systemctl enable --now auto-update.timer