#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

configure_flatpak() {
    [ "$FLATPAK_INSTALLED" = 1 ] || return 0

    info "Configuring flatpak"
    HUBS=$(flatpak remotes | cut -f 1 | grep ^flathub$)
    if [ -n "$HUBS" ]; then
        sudo flatpak remote-delete flathub
    fi
    sudo flatpak remote-add --if-not-exists --subset=verified flathub-verified https://dl.flathub.org/repo
    sudo flatpak remote-add --if-not-exists --filter=/home/markr/work/personal/credfeto-flatpak-filter/flatpak.filter flathub-whitelist https://dl.flathub.org/repo/

    # TODO: If can access https://flathub.markridgwell.com/repo/ then switch url
    sudo flatpak remote-modify --url=https://flathub.markridgwell.com/repo/ flathub-verified
    sudo flatpak remote-modify --url=https://flathub.markridgwell.com/repo/ flathub-whitelist
}

configure_flatpak
