#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

enable_services() {
    info "Enabling ssh-agent"
    systemctl enable --now --user ssh-agent

    info "Enabling apparmor"
    sudo systemctl enable --now apparmor.service
    sudo aa-enforce firejail-default

    info "Enabling logrotate"
    sudo pacman -S --needed --noconfirm logrotate
    sudo systemctl enable --now logrotate.timer
    sudo cp "$BASEDIR/settings/logrotate/01-defaults" /etc/logrotate.d/01-defaults

    info "Enabling pacman cache cleanup"
    sudo pacman -S --needed --noconfirm pacman-contrib
    sudo systemctl enable --now paccache.timer

    info "Installing pacman sync"
    sudo cp "$BASEDIR/units/pacman-sync/pacman-sync.service" /etc/systemd/system/
    sudo cp "$BASEDIR/units/pacman-sync/pacman-sync.timer" /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable --now pacman-sync.timer
}

enable_services
