#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

install_fail2ban() {
    info "Installing fail2ban"
    sudo cp "$BASEDIR/settings/fail2ban/default.local" "/etc/fail2ban/jail.d/default.local"
    sudo cp "$BASEDIR/settings/fail2ban/ssh.local" "/etc/fail2ban/jail.d/ssh.local"
    sudo pacman -S --needed --noconfirm fail2ban
    sudo systemctl enable --now fail2ban
}

install_fail2ban
