#!/bin/bash
sleep 2 && /bin/echo 1 > "/sys/devices/platform/thinkpad_acpi/leds/tpacpi::kbd_backlight/brightness"
sleep 2 && /bin/echo 2 > "/sys/devices/platform/thinkpad_acpi/leds/tpacpi::kbd_backlight/brightness"
